version: '3.8'

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGODB_INITDB_DATABASE: WebfluxDb
      MONGO_INITDB_ROOT_USERNAME: WebfluxDbUser
      MONGO_INITDB_ROOT_PASSWORD: WebfluxDbPassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: