spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: WebfluxDb
      username: WebfluxDbUser
      password: WebfluxDbPassword
      authentication-database: admin
      auto-index-creation: true